# Generated by Django 6.0.7 on 2026-07-09 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('cab', 'Cab'), ('bus', 'Bus'), ('private_car', 'Private Car'), ('other', 'Other')], default='other', max_length=32)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organizations.organization')),
            ],
        ),
    ]
