"""
Verification script for DrishtiRakshak AI LLM abstraction.
Runs a test sequence through LLMClient to verify generative pipelines
and rule-based fallbacks.
"""
import os
import sys

# Add the current directory to Python path to ensure clean imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Configure minimal settings dummy environment variables if Django isn't fully booted
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'drishtirakshak.settings')

import django
try:
    django.setup()
except Exception:
    # Fail gracefully if Django setup is not required for pure LLM testing
    pass

from detection.llm.client import LLMClient

def run_test():
    print("=" * 60)
    print("DrishtiRakshak AI - LLM Integration Verification")
    print("=" * 60)

    # 1. Instantiate our decoupled client
    client = LLMClient()

    # 2. Mock timeline events generated by the CV / detection layer
    mock_events = [
        {
            "offset": 1.2,
            "type": "vehicle_detected",
            "confidence": 0.94,
            "description": "Commercial vehicle detected close to camera view."
        },
        {
            "offset": 3.5,
            "type": "sustained_proximity",
            "confidence": 0.85,
            "description": "Tailgating behavior detected under low-visibility conditions."
        },
        {
            "offset": 5.0,
            "type": "sudden_deceleration",
            "confidence": 0.91,
            "description": "Abrupt brake indicator active in front zone."
        }
    ]

    # 3. Mock heuristic risk score generated by detection/risk.py
    mock_risk_score = 0.78

    print(f"\nSimulated Risk Score: {mock_risk_score}")
    print(f"Simulated Timeline Events Count: {len(mock_events)}")
    print("\nStarting generation process...")

    # 4. Generate the report summary
    summary = client.generate_summary(mock_events, mock_risk_score)

    print("\n" + "=" * 40)
    print("GENERATED SUMMARY REPORT:")
    print("=" * 40)
    print(summary)
    print("=" * 40 + "\n")

if __name__ == "__main__":
    run_test()