# Generated by Django 6.0.7 on 2026-07-09 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('logistics_fleet', 'Logistics Fleet'), ('cab_operator', 'Cab / Ride Operator'), ('school_transport', 'School Transport'), ('individual', 'Individual Vehicle Owner'), ('other', 'Other')], default='other', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_pilot', models.BooleanField(default=False, help_text='Marks this org as an active real-world pilot (vs. internal test data).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
