# Generated by Django 6.0.7 on 2026-08-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='analyst_notes',
            field=models.TextField(blank=True, default='', help_text='Free-text remarks entered by a human reviewer. Not AI-generated.'),
        ),
    ]
