# Generated by Django 6.0.7 on 2026-07-09 09:10

import django.db.models.deletion
import evidence.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to=evidence.models.evidence_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_offset_seconds', models.FloatField()),
                ('event_type', models.CharField(choices=[('vehicle_detected', 'Vehicle Detected'), ('person_detected', 'Person Detected'), ('sustained_proximity', 'Sustained Proximity'), ('sudden_deceleration', 'Sudden Deceleration'), ('other', 'Other')], max_length=32)),
                ('confidence', models.FloatField(help_text='0.0-1.0, from the detection/heuristic layer.')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('bounding_boxes', models.JSONField(blank=True, default=list)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='evidence.evidence')),
            ],
            options={
                'ordering': ['timestamp_offset_seconds'],
            },
        ),
    ]
