# Generated by Django 6.0.7 on 2026-07-28 08:01

import evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidence_error_message_evidence_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='video_file',
            field=models.FileField(max_length=500, upload_to=evidence.models.evidence_upload_path),
        ),
    ]
