# Generated by Django 6.0.7 on 2026-07-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidence_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='processing_status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NEW', max_length=20),
        ),
    ]
