# Generated by Django 6.0.7 on 2026-08-01 04:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_number', models.CharField(help_text='Police Control Room Reference ID', max_length=64, unique=True)),
                ('vehicle_plate', models.CharField(help_text='Vehicle License Plate Registration Number', max_length=64)),
                ('driver_name', models.CharField(default='Driver', help_text='Driver / Operator Name', max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(default=20.296)),
                ('longitude', models.FloatField(default=85.8245)),
                ('address', models.CharField(default='NH-16 Expressway, Km 42 (Bhubaneswar-Cuttack Corridor)', max_length=256)),
                ('threat_type', models.CharField(choices=[('STAGED_COLLISION_FRAUD', 'Intentional Pedestrian Obstruction (Staged Collision / Insurance Fraud)'), ('ROADBLOCK_ROBBERY_THREAT', 'Roadblock Obstruction / Robbery Attempt'), ('SUDDEN_DECELERATION_SPIKE', 'Sudden Emergency Deceleration Spike')], default='STAGED_COLLISION_FRAUD', max_length=64)),
                ('threat_category_label', models.CharField(blank=True, default='', max_length=256)),
                ('risk_score', models.FloatField(default=95.0, help_text='0-100 Threat Index Score')),
                ('status', models.CharField(choices=[('CRITICAL_SOS', 'Critical SOS Dispatch'), ('DISPATCHED', 'Patrol Unit En-Route'), ('CASE_SOLVED', 'Case Solved & Verified')], default='CRITICAL_SOS', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=128)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=128)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
