from rest_framework import viewsets

from incidents.models import Incident
from incidents.serializers import IncidentSerializer


class IncidentViewSet(viewsets.ReadOnlyModelViewSet):
    """Read-only: Incidents are generated by detection/pipeline.py, not created via the API."""

    queryset = Incident.objects.all()
    serializer_class = IncidentSerializer
